spring.datasource.url=jdbc:mysql://localhost:3306/chitra_realestate
spring.datasource.username=root
spring.datasource.password=Tony@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect